[project]
name = "approxssimate"
version = "0.2.0"
description = "Lightweight models for approximating SSIM from simpler distortion metrics"
authors = [
  {name = "Luc Trudeau"},
  {name = "Maria Martini"}
]
dependencies = [
  "av",
  "numpy",
  "scipy",
  "scikit-image",
]

[project.optional-dependencies]
test = ["pytest>=8"]

[project.scripts]
approxssimate = "approxssimate.cli:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["approxssimate"]

[tool.pytest.ini_options]
testpaths = ["tests"]
